/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro/index',
        'intro/overview',
      ],
    },
    {
      type: 'category',
      label: 'IEC 63430?',
      items: [
        'specification/index',
        'specification/spec_overview',
      ],
    },
    {
      type: 'category',
      label: 'Test Lab System',
      items: [
        'environment/index',
        'firststep/index',
        'expansion_guide/index',
      ],
    },
  ],
};

module.exports = sidebars;
